# Pipeline to check if solution builds and passes all unit tests
pool: Default

trigger: none #triggered by pull request azure branch policy

steps:
- task: UseDotNet@2
  displayName: Use .NET 7.X
  inputs:
    packageType: runtime
    version: '7.x'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*.csproj'
